### ISSUE TITLE
Can`t install plugins

### ISSUE THREAD

**Issue by ZataH** [ikogan/docker-openmediavault#1]
Hi i wanted to install the remoteshare plugin, but it wont let me, since it cant see PATH and apt. 
Any way around this?

**Comment by ikogan** [comment]
This should now be fixed in https://github.com/ikogan/docker-openmediavault/commit/55ec059a1d3ca62952c7b6836ca70d9937cc5d70. Sorry it took me a few days, I don't really use OpenMediaVault anymore so it's difficult to find the time but this turned out easy.

Apparently I had this problem on the live system when I was hacking on it and the solution was available in http://forum.openmediavault.org/index.php/Thread/8392-Install-of-OMV-extras-plugin-not-working-dpkg-error-PATH-is-not-set/.

New images are uploading now.
