### ISSUE TITLE
Wrong Ports Exposed

### ISSUE THREAD

**Issue by tshirtnjeans** [ikogan/docker-openmediavault#11]
Dockerfile exposes 8080 and 8443. This is incorrect as OMV uses 80 and 443 as noted.

**Comment by ikogan** [comment]
The documentation in the README is an example on _how_ to adjust the ports. The default ports in https://github.com/ikogan/docker-openmediavault/blob/master/container.ini are `8080` and `8443`. The startup script adjusts the ports [here](https://github.com/ikogan/docker-openmediavault/blob/master/omv-startup#L98).

This is handy to help run in a non-root environment when doing various bits of debugging and development. It seems true that the documentation is wrong and I'll adjust that.

Since I don't use OMV anymore I can't really do much about what happens if you _don't_ use 80 and 443.
